src/com/gamer/model/Basket.java
package com.gamer.model;

import java.util.HashMap;

import com.gamer.dao.DAOFactory;
import com.gamer.dao.ProductDAO;

public class Basket {
	
	private HashMap<Integer, ProductInBasket> basket = new HashMap<>();
	private int numProductsInBasket = 0;
	
	public Basket() { super(); }

	public void addOneToBasket(int productId) {
		boolean isAdded;
		if (basket.containsKey(productId)) {
			isAdded = basket.get(productId).addOneProduct();
		} else {
			ProductInBasket prod = new ProductInBasket();
			ProductDAO dao = DAOFactory.getInstance().getProductDAO();
			isAdded = prod.setProduct(dao.findProduct(productId));
			if (isAdded) basket.put(productId, prod);
		}
		if (isAdded) {
			numProductsInBasket++;
		}
	}
	
	public void removeOneFromBasket(int productId) {
		if (basket.containsKey(productId)) {
			if (basket.get(productId).getQuantity() > 1) {
				basket.get(productId).removeOneProduct();
				numProductsInBasket--;
			}
		}
	}
	
	public void removeAllFromBasket(int productId) {
		if (basket.containsKey(productId)) {
			numProductsInBasket -= basket.get(productId).getQuantity();
			basket.remove(productId);
		}
	}
	
	public ProductInBasket getProductInBasket(int productId) {
		return basket.get(productId);
	}
	
	public ProductInBasket[] getAllProductsInBasket() {
		return basket.values().toArray(new ProductInBasket[0]);
	}
	
	public int getTotalNumProductsInBasket() {
		return numProductsInBasket;
	}
	
	public double getTotalCostOfBasket() {
		double cost = 0;
		ProductInBasket[] products = getAllProductsInBasket();
		for (ProductInBasket product : products) {
			cost += product.getQuantity() * product.getProduct().getPrice();
		}
		return cost;
	}
	
	public boolean isInBasket(int productId) {
		return basket.containsKey(productId);
	}
	
	public void updateStock() {
		ProductDAO dao = DAOFactory.getInstance().getProductDAO();
		int id;
		for (ProductInBasket product : basket.values()) {
			id = product.getProduct().getId();
			product.getProduct().setStock(dao.findProductStock(id));
		}
	}
	
	public boolean checkEnoughStock() {
		ProductDAO dao = DAOFactory.getInstance().getProductDAO();
		int id;
		for (ProductInBasket product : basket.values()) {
			id = product.getProduct().getId();
			if (product.getQuantity() > dao.findProductStock(id)) {
				return false;
			}
		}
		return true;
	}
	
	public void emptyBasket() {
		basket.clear();
		numProductsInBasket = 0;
	}
}

src/com/gamer/model/Product.java
package com.gamer.model;

import java.io.Serializable;

public class Product implements Serializable {
	private static final long serialVersionUID = 1L;
	
	private String name;
	private String genre;
	private String description;
	private String pictureURI;
	private String type;
	private double price;
	private int stock;
	private int id;
	private boolean isInBasket;
	
	public Product() {super();}

	public String getName() {return name;}
	public void setName(String name) {this.name = name;}

	public String getGenre() {return genre;}
	public void setGenre(String genre) {this.genre = genre;}

	public String getDescription() {return description;}
	public void setDescription(String description) {this.description = description;}

	public String getPictureURI() {return pictureURI;}
	public void setPictureURI(String picURI) {this.pictureURI = picURI;}

	public double getPrice() {return price;}
	public void setPrice(double price) {this.price = price;}

	public int getStock() {return stock;}
	public void setStock(int stock) {this.stock = stock;}
	
	public int getId() {return id;}
	public void setId(int id) {this.id = id;}
	
	public String getType() {return type;}
	public void setType(String type) {this.type = type;}

	public boolean isInBasket() {return isInBasket;}
	public void setInBasket(boolean isInBasket) {this.isInBasket = isInBasket;}
}

WebContent/res/template/Footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page trimDirectiveWhitespaces="true" %>
<div id="footer">
<h3>GAMER.com</h3>
</div> <!-- END footer -->

WebContent/res/template/Header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page trimDirectiveWhitespaces="true" %>
<div id="header">
<h1>GAMER.com</h1>
</div> <!-- END header -->

WebContent/res/template/Nav.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<div id="nav">
	<ul>
		<li>
			<a id="home" href="/GAMER/shop?action=home">Home 
				<span class="status-info"></span>
			</a>
		</li>
		<li>
			<a id="toys" href="/GAMER/shop?action=toys">Toys 
				<span class="status-info"></span>
			</a>
		</li>
		<li>
			<a id="games" href="/GAMER/shop?action=games">Games 
				<span class="status-info"></span>
			</a>
		</li>
		<li>
			<a id="basket" href="/GAMER/shop?action=basket">Basket 
				<span class="status-info" id="basket-num">
					<c:choose>
						<c:when test="${not empty basket}">
							<c:out value="( ${basket.totalNumProductsInBasket} )"></c:out>
						</c:when>
						<c:otherwise>
							<c:out value="( 0 )"></c:out>
						</c:otherwise>
					</c:choose>
				</span>
			</a>
		</li>
	</ul>
</div> <!-- END nav -->

WebContent/res/template/PagesBar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:choose>
	<c:when test="${productViewHelper.totalNumberOfPages < 2}"/>
	<c:otherwise>
		<div id="pages-bar">
			<table>
				<tr>
					<td>
						<c:if test="${productViewHelper.currentPage != 1}">
							<form>
								<input type="hidden" name="action" value="${param['action']}"/>
								<c:if test="${not empty param['keywords']}">
									<input type="hidden" name="keywords" value="${param['keywords']}"/>
								</c:if>
								<input type="hidden" name="n" value="${productViewHelper.currentPage - 1}"/>	
								<input id="prev-page" type="submit" value="< prev page"/>
							</form>
						</c:if>
					</td>
					<td>
						<p>
							<c:forEach var="i" begin="1" end="${productViewHelper.totalNumberOfPages}">
								<c:choose>
									<c:when test="${i == productViewHelper.currentPage}">
										<span id="current-page">
											<c:out value="${i}"/>
										</span>
									</c:when>
									<c:otherwise>
										<c:out value="${i}"/>
									</c:otherwise>
								</c:choose>
							</c:forEach>
						</p>
					</td>
					<td>
						<c:if test="${productViewHelper.currentPage != productViewHelper.totalNumberOfPages}">
							<form>
								<input type="hidden" name="action" value="${param['action']}"/>
								<c:if test="${not empty param['keywords']}">
									<input type="hidden" name="keywords" value="${param['keywords']}"/>
								</c:if>
								<input type="hidden" name="n" value="${productViewHelper.currentPage + 1}"/>	
								<input id="next-page" type="submit" value="next page >"/>
							</form>
						</c:if>
					</td>
				</tr>
			</table>
		</div>
	</c:otherwise>
</c:choose>

WebContent/res/template/ProductDisplay.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<script src="/GAMER/res/js/basket.js"></script>
<c:forEach var="product" items="${productViewHelper.productsForPage}">
	<div class="prod">
		<div class="highlight">
			<div class="prod-img" style="background-image:url(${product.pictureURI});">
				<img id="add-basket-${product.id}" class="add-bask-img" src="/GAMER/res/img/misc/AddedToBasket.png" <c:if test="${!product.inBasket}">style="display:none;"</c:if>>
			</div>
			<h2>${product.name}</h2>
			<table>
				<tr>
					<td class="price"><h2>£ ${product.price}0</h2></td>
					<td class="prod-stock">${product.stock} in stock</td>
				</tr>
			</table>
			<button class="basket_button" id="${product.id}">Add to Basket</button>
		</div>
	</div>
</c:forEach>

WebContent/res/template/TopBar.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page trimDirectiveWhitespaces="true" %>
<div id="top-bar">
<div id="inner-top-bar">
<table>
<tr>
<td>
	<c:if test="${not empty loggedInCustomer.forename}">logged in as ${loggedInCustomer.forename}</c:if>
</td>
<td>
	<form method="post" action="shop?action=search">
		<input id="search-field" type="text" size="32" name="keywords"/>
		<input id="search-button" type="submit" value=" " />
	</form>
</td>
<td>
	<c:choose>
		<c:when test="${empty loggedInCustomer}">
			<a href="/GAMER/shop?action=login">login</a>
		</c:when>
		<c:otherwise>
			<a href="/GAMER/shop?action=logout">logout</a>
		</c:otherwise>
	</c:choose>
</td>
<td><a href="/GAMER/shop?action=register">register</a></td>
</tr>
</table>
</div> <!-- END inner-top-bar -->
</div> <!-- END top-bar -->