src/com/gamer/model/Basket.java
package com.gamer.model;

import java.util.HashMap;

import com.gamer.dao.DAOFactory;
import com.gamer.dao.ProductDAO;

public class Basket {
	
	private HashMap<Integer, ProductInBasket> basket = new HashMap<>();
	private int numProductsInBasket = 0;
	
	public Basket() { super(); }

	public void addOneToBasket(int productId) {
		boolean isAdded;
		if (basket.containsKey(productId)) {
			isAdded = basket.get(productId).addOneProduct();
		} else {
			ProductInBasket prod = new ProductInBasket();
			ProductDAO dao = DAOFactory.getInstance().getProductDAO();
			isAdded = prod.setProduct(dao.findProduct(productId));
			if (isAdded) basket.put(productId, prod);
		}
		if (isAdded) {
			numProductsInBasket++;
		}
	}
	
	public void removeOneFromBasket(int productId) {
		if (basket.containsKey(productId)) {
			if (basket.get(productId).getQuantity() > 1) {
				basket.get(productId).removeOneProduct();
				numProductsInBasket--;
			}
		}
	}
	
	public void removeAllFromBasket(int productId) {
		if (basket.containsKey(productId)) {
			numProductsInBasket -= basket.get(productId).getQuantity();
			basket.remove(productId);
		}
	}
	
	public ProductInBasket getProductInBasket(int productId) {
		return basket.get(productId);
	}
	
	public ProductInBasket[] getAllProductsInBasket() {
		return basket.values().toArray(new ProductInBasket[0]);
	}
	
	public int getTotalNumProductsInBasket() {
		return numProductsInBasket;
	}
	
	public double getTotalCostOfBasket() {
		double cost = 0;
		ProductInBasket[] products = getAllProductsInBasket();
		for (ProductInBasket product : products) {
			cost += product.getQuantity() * product.getProduct().getPrice();
		}
		return cost;
	}
	
	public boolean isInBasket(int productId) {
		return basket.containsKey(productId);
	}
	
	public void updateStock() {
		ProductDAO dao = DAOFactory.getInstance().getProductDAO();
		int id;
		for (ProductInBasket product : basket.values()) {
			id = product.getProduct().getId();
			product.getProduct().setStock(dao.findProductStock(id));
		}
	}
	
	public boolean checkEnoughStock() {
		ProductDAO dao = DAOFactory.getInstance().getProductDAO();
		int id;
		for (ProductInBasket product : basket.values()) {
			id = product.getProduct().getId();
			if (product.getQuantity() > dao.findProductStock(id)) {
				return false;
			}
		}
		return true;
	}
	
	public void emptyBasket() {
		basket.clear();
		numProductsInBasket = 0;
	}
}

src/com/gamer/model/Product.java
package com.gamer.model;

import java.io.Serializable;

public class Product implements Serializable {
	private static final long serialVersionUID = 1L;
	
	private String name;
	private String genre;
	private String description;
	private String pictureURI;
	private String type;
	private double price;
	private int stock;
	private int id;
	private boolean isInBasket;
	
	public Product() {super();}

	public String getName() {return name;}
	public void setName(String name) {this.name = name;}

	public String getGenre() {return genre;}
	public void setGenre(String genre) {this.genre = genre;}

	public String getDescription() {return description;}
	public void setDescription(String description) {this.description = description;}

	public String getPictureURI() {return pictureURI;}
	public void setPictureURI(String picURI) {this.pictureURI = picURI;}

	public double getPrice() {return price;}
	public void setPrice(double price) {this.price = price;}

	public int getStock() {return stock;}
	public void setStock(int stock) {this.stock = stock;}
	
	public int getId() {return id;}
	public void setId(int id) {this.id = id;}
	
	public String getType() {return type;}
	public void setType(String type) {this.type = type;}

	public boolean isInBasket() {return isInBasket;}
	public void setInBasket(boolean isInBasket) {this.isInBasket = isInBasket;}
}

src/com/gamer/model/ProductInBasket.java
package com.gamer.model;

import java.io.Serializable;

public class ProductInBasket implements Serializable {
	private static final long serialVersionUID = 1L;
	
	private Product product;
	private int quantity;
	
	public Product getProduct() { return product; }
	public boolean setProduct(Product product) {
		if (product.getStock() == 0) return false;
		this.product = product;
		quantity = 1;
		return true;
	}
	
	public int getQuantity() { return quantity; }
	public void setQuantity(int quantity) { this.quantity = quantity; }
	
	public double getLinePrice() {
		return product.getPrice() * quantity;
	}
	
	public boolean addOneProduct() { 
		if (quantity < product.getStock()) {
			quantity++;
			return true;
		}
		return false;
	}
	
	public void removeOneProduct() { 
		if (quantity > 0) quantity--;
	}
	
	public boolean isEnoughStock() {
		return quantity <= product.getStock();
	}
}

src/com/gamer/controller/BasketController.java
package com.gamer.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.gamer.model.Basket;
import com.gamer.viewhelper.BasketViewHelper;
import com.gamer.viewhelper.ViewHelperFactory;

/**
 * 
 */
@WebServlet("/basketController")
public class BasketController extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public BasketController() { super(); }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest req, HttpServletResponse res)
	 */
	protected void doGet(HttpServletRequest req, HttpServletResponse res) 
			throws ServletException, IOException {
		doPost(req, res);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest req, HttpServletResponse res)
	 */
	protected void doPost(HttpServletRequest req, HttpServletResponse res) 
			throws ServletException, IOException {
		
		String action = (String)req.getParameter("action");
		if (action == null) action = "";

		if (req.getSession().getAttribute("basket") == null) {
			req.getSession().setAttribute("basket", new Basket());
		}
		
		BasketViewHelper basketViewHelper = 
				ViewHelperFactory.getInstance().getBasketViewHelper(req);
		
		String json;
		
		switch (action) {
		case "basket":
			String url = "/";
			if (basketViewHelper.basketIsEmpty()) {
				req.setAttribute("msg", "There are currently no items in your basket");
				req.setAttribute("link", "back to "
						+ "<a href=\"/GAMER/shop?action=home\">shopping</a>");
				url += "UserMsg.jsp";
			}
			else {
				url += "Basket.jsp";
			}
			getServletContext().getRequestDispatcher(url).forward(req, res);
			break;
		
		case "add-to-basket":
			json = basketViewHelper.addOneToBasket();
				
			res.setContentType("application/json");
		    res.setCharacterEncoding("UTF-8");
		    res.getWriter().write(json);
			break;

		case "rem-from-basket":
			json = basketViewHelper.removeOneFromBasket();
				
			res.setContentType("application/json");
			res.setCharacterEncoding("UTF-8");
			res.getWriter().write(json);
			break;
			
		case "del-from-basket":
			json = basketViewHelper.removeAllFromBasket();
				
			res.setContentType("application/json");
			res.setCharacterEncoding("UTF-8");
			res.getWriter().write(json);
			break;
		}
	}
}

src/com/gamer/controller/LoginController.java
package com.gamer.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.gamer.dao.DAOFactory;
import com.gamer.model.Customer;
import com.gamer.viewhelper.LoginViewHelper;
import com.gamer.viewhelper.ViewHelperFactory;

/**
 * 
 */
@WebServlet("/loginController")
public class LoginController extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public LoginController() {super();}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest req, HttpServletResponse res)
	 */
	protected void doGet(HttpServletRequest req, HttpServletResponse res) 
			throws ServletException, IOException {
		doPost(req, res);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest req, HttpServletResponse res)
	 */
	protected void doPost(HttpServletRequest req, HttpServletResponse res) 
			throws ServletException, IOException {
		
		HttpSession session = req.getSession(true);
		
		String url = "/";
		
		String action = (String)req.getParameter("action");
		
		LoginViewHelper loginViewHelper = 
				ViewHelperFactory.getInstance().getLoginViewHelper(req);
		req.setAttribute("loginViewHelper", loginViewHelper);
		
		switch (action) {
		case "login":
			url += "Login.jsp";
			break;

		case "login-submit":
			if (loginViewHelper.containsValidLoginDetails()
					&& loginViewHelper.emailPasswordComboIsInDatabase()) {
				Customer customer = DAOFactory.getInstance().getCustomerDAO()
						.findCustomerByEmail(loginViewHelper.getEmail());
				session.setAttribute("loggedInCustomer", customer);
				
				if ("purchase".equals(req.getParameter("requestAction"))) {
					url += "purchaseController";
				}
				else {
					req.setAttribute("msg", "" + customer.getForename() 
							+ ", welcome back to GAMER.com !");
					req.setAttribute("link", "start shopping "
							+ "<a href=\"/GAMER/shop?action=home\">here</a>");
					url += "UserMsg.jsp";
				}
			}
			else {
				if ("purchase".equals(req.getParameter("requestAction"))) {
					req.setAttribute("requestAction", "purchase");
				}
				url += "LoginSubmitted.jsp";
			}
			break;
		}
		
		getServletContext().getRequestDispatcher(url).forward(req, res);
	}
}

src/com/gamer/controller/RegisterController.java
package com.gamer.controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.gamer.dao.DAOFactory;
import com.gamer.model.Customer;
import com.gamer.viewhelper.RegisterViewHelper;
import com.gamer.viewhelper.ViewHelperFactory;

/**
 * 
 */
@WebServlet("/registerController")
public class RegisterController extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public RegisterController() {super();}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest req, HttpServletResponse res)
	 */
	protected void doGet(HttpServletRequest req, HttpServletResponse res) 
			throws ServletException, IOException {
		doPost(req, res);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest req, HttpServletResponse res)
	 */
	protected void doPost(HttpServletRequest req, HttpServletResponse res) 
			throws ServletException, IOException {
		
		HttpSession session = req.getSession();
		
		String url = "/";
		
		String action = (String)req.getParameter("action");
		
		RegisterViewHelper registerViewHelper = 
				ViewHelperFactory.getInstance().getRegisterViewHelper(req);
		req.setAttribute("registerViewHelper", registerViewHelper);
		
		switch (action) {
		case "register":
			url += "Register.jsp";
			break;

		case "register-submit":
			if (registerViewHelper.containsValidCustomerDetails()
					&& !registerViewHelper.isEmailInDatabase()) {

				Customer customer = registerViewHelper.createCustomer();
				int id = DAOFactory.getInstance().getCustomerDAO()
						.insertCustomer(customer);
				customer.setId(id);
				session.setAttribute("loggedInCustomer", customer);
				
				if ("purchase".equals(req.getParameter("requestAction"))) {
					url += "purchaseController";
				}
				else {
					req.setAttribute("msg", "Hi " + customer.getForename() 
							+ ", welcome to GAMER.com !");
					req.setAttribute("link", "start shopping "
							+ "<a href=\"/GAMER/shop?action=home\">here</a>");
					url += "UserMsg.jsp";
				}
			} 
			else {
				if ("purchase".equals(req.getParameter("requestAction"))) {
					req.setAttribute("requestAction", "purchase");
				}
				url += "RegisterSubmitted.jsp";
			}
			break;
		}
		
		getServletContext().getRequestDispatcher(url).forward(req, res);
	}
}

WebContent/Basket.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page trimDirectiveWhitespaces="true" %>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>GAMER.com</title>
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Theme.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/TopBar.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Header.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Nav.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Content.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Basket.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/UserMsg.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Footer.css">
		<script src="/GAMER/res/js/lib/jquery-1.11.0.js"></script>
		<script src="/GAMER/res/js/basket.js"></script>
	</head>
	<body class="basket">
		<jsp:include page="/res/template/TopBar.jsp" flush="true"/>
		<jsp:include page="/res/template/Header.jsp" flush="true"/>
		<jsp:include page="/res/template/Nav.jsp" flush="true"/>
		<div id="content">
			<div id="basket-content">
				<c:if test="${purchaseStockIssue == 'notEnoughStock'}">
					<p id="stock-issue">unfortunately the available stock has reduced for some of your items</p>
				</c:if>
				<table id="bask-tab">
					<thead>
						<tr>
							<th class="bask-item, heading">Basket Item</th>
							<th class="bask-spacer heading"> </th>
							<th> </th>
							<th class="heading" colspan="3">Quantity</th>
							<th> </th>
							<th> </th>
							<th class="line-price heading">Price</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<td> </td>
							<td class="bask-spacer"> </td>
							<td colspan="5"></td>
							<td id="bask-total-lab">total:</td>
							<td id="bask-total-fig" class="line-price">£ ${basket.totalCostOfBasket}0</td>
						</tr>
					</tfoot>
					<tbody>
					<c:forEach var="product" items="${basket.allProductsInBasket}">
						<tr id="row-${product.product.id}">
							<td class="bask-item">
								<c:out value="${product.product.name}"/>
							</td>
							<td class="bask-spacer"></td>
							<c:choose>
								<c:when test="${product.enoughStock}">
									<td class="stock">${product.product.stock} in stock</td>
								</c:when>
								<c:otherwise>
									<td class="stock stock-warning">not enough stock,<br/>only ${product.product.stock} available</td>
								</c:otherwise>
							</c:choose>
							<td>
								<input class="quan-min" type="submit" value="-" name="${product.product.id}"/>
							</td>
							<td>
								<input id="quan-${product.product.id}" class="quan" type="text" name="quantity" value="${product.quantity}" readonly/>
							</td>
							<td>
								<input class="quan-plus" type="submit" value="+" name="${product.product.id}"/>
							</td>
							<td>
								<input class="rem-item" type="submit" value="remove item" name="${product.product.id}"/>
							</td>
							<td> </td>
							<td id="line-price-${product.product.id}" class="line-price">
								<c:out value="£ ${product.linePrice}0"/>
							</td>
						</tr>
					</c:forEach>
					</tbody>
				</table>
				<table>
					<tr>
						<td id="purchase">
							<form action="shop" method="get">
								<input type="hidden" name="action"	value="purchase">
								<input id="pur-button" type="submit" value="Purchase"/>
							</form>
						</td>
					</tr>
				</table>
			</div>
		</div> <!-- END content -->
		<jsp:include page="/res/template/Footer.jsp" flush="true"/>
	</body>
</html>

WebContent/Login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page trimDirectiveWhitespaces="true" %>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>GAMER.com</title>
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Theme.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/TopBar.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Header.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Nav.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Content.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Footer.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/LoginRegister.css">
		<script src="/GAMER/res/js/lib/jquery-1.11.0.js"></script>
		<script src="/GAMER/res/js/register.js"></script>
	</head>
	<body class="login">
		<jsp:include page="/res/template/TopBar.jsp" flush="true"/>
		<jsp:include page="/res/template/Header.jsp" flush="true"/>
		<jsp:include page="/res/template/Nav.jsp" flush="true"/>
		<div id="content">
			<div id="reg-cont">
				<c:if test="${requestAction == 'purchase'}">
					<p>you need to login or register before you purchase</p>
				</c:if>
				<form method="post" action="shop?action=login-submit" accept-charset="UTF-8">
					<fieldset class="reg-log">
						<legend>Login</legend>
						<table>
							<tr>
								<td class="input-title">E-mail:</td>
								<td class="input"><input type="text" maxlength="100" name="email"></td>
								<td class="input-spacer"></td>
							</tr>
							<tr id="email-error" class="error" style="display:none;">
								<td colspan="3">${loginViewHelper.emailErrorMsg}</td>
							</tr>
							<tr>
								<td class="input-title">Password:</td>
								<td class="input"><input type="password" maxlength="16" name="password"></td>
								<td class="input-spacer"></td>
							</tr>
							<tr id="password-error" class="error" style="display:none;">
								<td colspan="3">${loginViewHelper.passwordErrorMsg}</td>
							</tr>
						</table>
					</fieldset>
					<c:if test="${requestAction == 'purchase'}">
						<input type="hidden" name="requestAction" value="purchase">
					</c:if>
					<input id="submit" type="submit" value="Submit" />
				</form>
				<c:choose>
					<c:when test="${requestAction == 'purchase'}">
						<p>If you're not registered then go ahead and <a href="/GAMER/shop?action=register&requestAction=purchase">register</a> now.</p>
					</c:when>
					<c:otherwise>
						<p>If you're not registered then go ahead and <a href="/GAMER/shop?action=register">register</a> now.</p>
					</c:otherwise>
				</c:choose>
			</div>
		</div> <!-- END content -->
		<jsp:include page="/res/template/Footer.jsp" flush="true"/>
	</body>
</html>

WebContent/LoginSubmitted.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page trimDirectiveWhitespaces="true" %>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>GAMER.com</title>
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Theme.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/TopBar.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Header.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Nav.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Content.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Footer.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/LoginRegister.css">
		<script src="/GAMER/res/js/lib/jquery-1.11.0.js"></script>
		<script src="/GAMER/res/js/register.js"></script>
	</head>
	<body class="login">
		<jsp:include page="/res/template/TopBar.jsp" flush="true"/>
		<jsp:include page="/res/template/Header.jsp" flush="true"/>
		<jsp:include page="/res/template/Nav.jsp" flush="true"/>
		<div id="content">
			<div id="reg-cont">
				<c:if test="${requestAction == 'purchase'}">
					<p>you need to login or register before you purchase</p>
				</c:if>
				<form method="post" action="shop?action=login-submit" accept-charset="UTF-8">
					<fieldset class="reg-log">
						<legend>Login</legend>
						<table>
							<tr>
								<td class="input-title">E-mail:</td>
								<td class="input"><input type="text" maxlength="100" name="email" value="${loginViewHelper.email}"></td>
								<td class="input-spacer"></td>
							</tr>
							<tr id="email-error" class="error" <c:if test="${loginViewHelper.validEmail}">style="display:none;"</c:if>>
								<td colspan="3">${loginViewHelper.emailErrorMsg}</td>
							</tr>
							<tr>
								<td class="input-title">Password:</td>
								<td class="input"><input type="password" maxlength="16" name="password" value="${loginViewHelper.password}"></td>
								<td class="input-spacer"></td>
							</tr>
							<tr id="password-error" class="error" <c:if test="${loginViewHelper.validPassword}">style="display:none;"</c:if>>
								<td colspan="3">${loginViewHelper.passwordErrorMsg}</td>
							</tr>
							<tr id="password-not-found-error" class="error" <c:if test="${ !loginViewHelper.validPassword || !loginViewHelper.validEmail}">style="display:none;"</c:if>>
								<td colspan="3">${loginViewHelper.passwordNotFoundErrorMsg}</td>
							</tr>
						</table>
					</fieldset>
					<c:if test="${requestAction == 'purchase'}">
						<input type="hidden" name="requestAction" value="purchase">
					</c:if>
					<input id="submit" type="submit" value="Submit" />
				</form>
				<c:choose>
					<c:when test="${requestAction == 'purchase'}">
						<p>If you're not registered then go ahead and <a href="/GAMER/shop?action=register&requestAction=purchase">register</a> now.</p>
					</c:when>
					<c:otherwise>
						<p>If you're not registered then go ahead and <a href="/GAMER/shop?action=register">register</a> now.</p>
					</c:otherwise>
				</c:choose>
			</div>
		</div> <!-- END content -->
		<jsp:include page="/res/template/Footer.jsp" flush="true"/>
	</body>
</html>

WebContent/ProductView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page trimDirectiveWhitespaces="true" %>
<c:if test="${empty productViewHelper}">
	<jsp:forward page="/shop?action=home"/>
</c:if>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>GAMER.com</title>
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Theme.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/TopBar.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Header.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Nav.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Content.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Footer.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Product.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/PagesBar.css">
		<script src="/GAMER/res/js/lib/jquery-1.11.0.js"></script>
	</head>
	<body class="${productViewType}">
		<jsp:include page="/res/template/TopBar.jsp" flush="true"/>
		<jsp:include page="/res/template/Header.jsp" flush="true"/>
		<jsp:include page="/res/template/Nav.jsp" flush="true"/>
		<div id="content">
			<jsp:include page="/res/template/ProductDisplay.jsp" flush="true"/>
			<jsp:include page="/res/template/PagesBar.jsp" flush="true"/>
		</div> <!-- END content -->
		<jsp:include page="/res/template/Footer.jsp" flush="true"/>
	</body>
</html>

WebContent/UserMsg.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page trimDirectiveWhitespaces="true" %>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>GAMER.com</title>
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Theme.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/TopBar.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Header.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Nav.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Content.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/Footer.css">
		<link rel="stylesheet" type="text/css" href="/GAMER/res/css/UserMsg.css">
	</head>
	<body>
		<jsp:include page="/res/template/TopBar.jsp" flush="true"/>
		<jsp:include page="/res/template/Header.jsp" flush="true"/>
		<jsp:include page="/res/template/Nav.jsp" flush="true"/>
		<div id="content">
			<div id="inner-content">
				<p id="msg"><c:out value="${msg}"/></p>
				<p id="link">${link}</p>
			</div>
		</div> <!-- END content -->
		<jsp:include page="/res/template/Footer.jsp" flush="true"/>
	</body>
</html>

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<% response.sendRedirect("/GAMER/shop?action=home"); %>